### ISSUE TITLE
Need some help to compile this

### ISSUE THREAD

**Issue by qunwoods** [ttnghia/SimpleSPH#1]
Could you show me how to compile this project ? Thanks

**Comment by ttnghia** [comment]
Hi. 
In order to compile this program, you must install Qt5 first (https://www.qt.io/).
However, the program needs to include code from my other repository (https://github.com/ttnghia/Banana), which is also required to compile. Unfortunately, Banana has been deprecated and cannot compile now.
If you can wait, I can rewrite this repository for you so you can compile by yourself easier. I can do it next weekend.

**Comment by qunwoods** [comment]
Thank you very much for your reply. 
I downloaded QT5.9.2, and tried to compile banana in recent days. I compiled some libraries through VS2017. When compiling water simulation and water rendering projects, I found that some files were missing. 
Is there a heavy workload for rewriting this repository? I'm sorry to increase your workload and I really appreciate your help.




在2018年11月06 01时59分, "Nghia Truong"<notifications@github.com>写道:



Hi.
In order to compile this program, you must install Qt5 first (https://www.qt.io/).
The program also needs to include code from my other repository (https://github.com/ttnghia/Banana), which is also required to compile. Unfortunately, Banana has been deprecated and cannot compile now.
If you can wait, I can rewrite this repository for you so you can compile by yourself easier. I can do it next weekend.

**Comment by qunwoods** [comment]
Thank you very much for your reply. I downloaded QT5.9.2, and tried to compile banana in recent days. I compiled some libraries through VS2017. When compiling water simulation and water rendering projects, I found that some files were missing. Is there a heavy workload for rewriting this repository? I'm sorry to increase your workload and I really appreciate your help.
And I'm very sorry that I didn't see your reply before, so I sent you an email again.

**Comment by qunwoods** [comment]
I'm very sorry that I didn't see your reply before, so I sent you an email again.

**Comment by ttnghia** [comment]
No problem. I will rewrite it anyway. I'm not sure when I can make it done, but should not very long. Stay updated :)

**Comment by qunwoods** [comment]
Hello, I'm sorry to interrupt you.  I wonder if you have time to update the banana project recently?

**Comment by ttnghia** [comment]
I am sorry, I tried to work on it but it seems to take more time than expected. I would probably need a couple of days for it, but I have some emergent tasks need to be done with a strict deadline thus I had to delay it. Currently, I'm working on my Siggraph submission and will definitely make this done after I submit my paper.

**Comment by qunwoods** [comment]
Wow, Siggraph! That's the most important thing. Thank you very much for your help and wish you every success.
